Traceback (most recent call last):
  File "./GrosseBite.py", line 46, in <module>
    checkPiece(a)
  File "./GrosseBite.py", line 16, in checkPiece
    for line in fileinput.input():
  File "/usr/lib/python3.8/fileinput.py", line 248, in __next__
    line = self._readline()
KeyboardInterrupt
GAME: SEND TO 20247: START 14

GAME: SEND TO 20247: PLAYER 0

GAME: SEND TO 20260: START 14

GAME: SEND TO 20260: PLAYER 1

GAME: SEND TO 20247: PLAY

GAME: RECEIVE FROM 20247: PIECES

GAME: SEND TO 20247: 1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21

GAME: SEND TO 20247: DONE

GAME: RECEIVE FROM 20247: PLAY 21 4 3 0

GAME: SEND TO 20260: PLAYED 0 21 4 3 0

GAME: SEND TO 20247: DONE

GAME: SEND TO 20260: PLAY

Traceback (most recent call last):
  File "main.py", line 31, in <module>
    main()
  File "main.py", line 24, in main
    asyncio.run(game.run())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
CLIENT 20247: RECEIVE: START 14

CLIENT 20247: RECEIVE: PLAYER 0

CLIENT 20247: RECEIVE: PLAY

CLIENT 20247: SEND: PIECES
CLIENT 20247: RECEIVE: 1
CLIENT 20247: RECEIVE: 2
CLIENT 20247: RECEIVE: 3
CLIENT 20247: RECEIVE: 4
CLIENT 20247: RECEIVE: 5
CLIENT 20247: RECEIVE: 6
CLIENT 20247: RECEIVE: 7
CLIENT 20247: RECEIVE: 8
CLIENT 20247: RECEIVE: 9
CLIENT 20247: RECEIVE: 10
CLIENT 20247: RECEIVE: 11
CLIENT 20247: RECEIVE: 12
CLIENT 20247: RECEIVE: 13
CLIENT 20247: RECEIVE: 14
CLIENT 20247: RECEIVE: 15
CLIENT 20247: RECEIVE: 16
CLIENT 20247: RECEIVE: 17
CLIENT 20247: RECEIVE: 18
CLIENT 20247: RECEIVE: 19
CLIENT 20247: RECEIVE: 20
CLIENT 20247: RECEIVE: 21
CLIENT 20247: RECEIVE: DONE
CLIENT 20247: SEND: PLAY 21 4 3 0
Traceback (most recent call last):
  File "/home/benjamin/AI-blokus-tournament/basic-ai/Homer.py", line 146, in <module>
  File "/home/benjamin/AI-blokus-tournament/basic-ai/Homer.py", line 134, in main
  File "/home/benjamin/AI-blokus-tournament/basic-ai/Homer.py", line 120, in get_line
KeyboardInterrupt
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 20260 is closed
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 20247 is closed
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7f0892791a60>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_subprocess.py", line 126, in __del__
  File "/usr/lib/python3.8/asyncio/base_subprocess.py", line 104, in close
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 735, in close
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 721, in write_eof
  File "/usr/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7f0892791a60>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_subprocess.py", line 126, in __del__
  File "/usr/lib/python3.8/asyncio/base_subprocess.py", line 104, in close
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 735, in close
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 721, in write_eof
  File "/usr/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
